# Laboratorio 4 | Machine Learning
* Marco Ferraro | B82957
* Roy Padilla | B85854

In [1]:
import pandas as pd # procesamiento de dataset
import math # uso de función exp
import numpy as np # uso de funciones y generación de arreglos
import math # operación de raíz cuadrada

LIMIT = 1e-5

In [2]:
target_value_titanic = ['Survived_0', 'Survived_1']
df_titanic = pd.read_csv('titanic.csv')
df_titanic = df_titanic.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin']).dropna()

# Se pasan a one-hot encoding las columnas 'Pclass','Sex' y 'Survived'
df_titanic = pd.get_dummies(df_titanic,columns=['Embarked', 'Pclass','Sex', 'Survived'])
y = df_titanic.loc[:, target_value_titanic]


df_titanic = df_titanic.drop(columns = target_value_titanic)

df_titanic.shape

(1043, 12)

1. Función `sigmoid(x)` que recibe un número `x` y retorna el resultado de la función sigmoide para dicho `x:   1/(1 + e^(-x))`


In [3]:
def sigmoid(x):
  try:
    return 1 / (1 + np.exp(-x))
  except OverflowError:
    return LIMIT

2. Función d_sigmoid(y) que recibe un número y (tal que y = sigmoid(x)) y retorna el resultado de la derivada de la función sigmoide para el y dado: y*(1-y)


In [4]:
def d_sigmoid(y):
  try:
    return y * (1 - y)
  except OverflowError:
    return LIMIT

3. Función `tanh(x)` que recibe un número x y retorna el resultado de la función tangente hiperbólico para dicho `x: (e^x - e^(-x))/(e^x + e^(-x))`

In [5]:
def tanh(x):
  try:
    return (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))
  except OverflowError:
    return LIMIT

4. Función `d_tanh(y)` que recibe un número y (tal que `y = tanh(x)`) y retorna el resultado de la derivada de la función tangente hiperbólico para el `y` dado: `1 - y^2`

In [6]:
def d_tanh(y):
  try:
    return 1-y**2
  except OverflowError:
    return LIMIT

5. Función `relu(x)` que recibe un número x y retorna el resultado de la función lineal rectificada para dicho `x: (x if x > 0 else 0)`

In [7]:
def relu(x):
  try:
    return x if x > 0 else 0
  except OverflowError:
    return LIMIT

6. Función `d_relu(y)` que recibe un número `y` (tal que `y = relu(x)`) y retorna el resultado de la derivada de la función lineal rectificada para el y dado: `1 if y >0 else 0`

In [8]:
def d_relu(y):
  try:
    return 1 if y > 0 else 0
  except OverflowError:
    return LIMIT

7. `Función lrelu(x)` que recibe un número x y retorna el resultado de la función lineal rectificada con fuga para dicho x: (x if x>0 else 0.01x)

In [9]:
def lrelu(x):
  try:
    return x if x>0 else 0.01*x
  except OverflowError:
    return LIMIT

8. Función `d_lrelu(y)` que recibe un número y (tal que y = lrelu(x)) y retorna el resultado de la derivada de la función lineal rectificada con fuga para el y dado: 1 if y>0 else 0.01

In [10]:
def d_lrelu(y):
  try:
    return 1 if y > 0 else 0.01
  except OverflowError:
    return LIMIT

`Clase DenseNN`


10. `Método predict(self, x)` que recibe una matriz de datos x de tamaño nxm, donde m coincide con el primer valor de layers al construir la red neuronal. Este método ejecuta el forward propagation aplicando la multiplicación con la matrices de pesos y las funciones de activación de cada capa. Finalmente, retorna una matriz de datos nxp, donde p coincide con el último de layers y corresponde a los valores predichos por la red neuronal para los casos x.

In [11]:
class DenseNN:
    def __init__(self, layers, activation, seed = 0):
      np.random.seed(seed)

      self.x_count = layers[0]
      self.y_count = layers[-1]
      self.activation = activation
      self.epoch = 0
      self.momentum = 0
      self.lr = 0
      self.decay = 0

      self.weight_matrixs = []
      self.delta_weight_matrix = []
      
      self.net_values = []
      self.activation_values = []
      self.layers_errors = []

      self.activation_values_reduced = []
      self.layers_errors_reduced = []

      self.error_history = []

      # inicialización de la matriz de pesos y bias
      for index in range(len(layers[1:])):
        fan_in = layers[index] # capa anterior (cantidad de columnas)
        fan_out = 0 if len(layers[1:-1]) < index + 1 else layers[index+2] # capa siguiente
        self.weight_matrixs.append(np.random.normal(loc = 0, scale=2.0/math.sqrt(fan_in + fan_out), size = (fan_in + 1, layers[index + 1])))

    def predict(self, x = pd.DataFrame):
      x = x.assign(bias = np.ones(x.shape[0])) # inserción del bias
      predictions = np.array([])
      for index, row in x.iterrows():
        # llamada al forward propagation para la fila
        predictions = np.append(predictions, self._fowardPropagation(row))
      return predictions 

    def train(self, lr=0.05, momentum=0, decay=0):
      self.epoch = 0
      self.error_history = []
      # REVISAR
      self.lr = lr
      self.momentum = momentum
      self.decay = decay
      self.delta_weight_matrix = []
      for weight_matrix in self.weight_matrixs:
        self.delta_weight_matrix.append(np.copy(weight_matrix))

    def _fowardPropagation(self, row):
      # limpieza de los valores netos, activación y error
      # self.activation_values = []
      self.net_values = []
      
      # inicialización de los valores para la primer capa oculta
      net_k = np.matmul(np.transpose(row.to_numpy()), self.weight_matrixs[0])
      o_k = self._getActivationValue(0, net_k)
      
      self.net_values.append(net_k)
      
      # recorrido desde la segunda capa oculta hasta la salida
      for weight_index in range(len(self.weight_matrixs[1:])):
        # aplicación de la multiplicación: x*w
        net_k = np.matmul(np.transpose(np.append(o_k, 1)), self.weight_matrixs[weight_index + 1])
        # Aplicación de la función de activación en cada uno de los resultados
        o_k = self._getActivationValue(weight_index + 1, net_k)
        self.net_values.append(net_k)

      # Retorna el valor final de la predicción de la tupla
      return o_k

    def backPropagation(self, x, y):
      x = x.assign(bias = np.ones(x.shape[0]))

      self.layers_errors = [np.array([])] * len(self.weight_matrixs)
      self.activation_values = [np.array([])] * len(self.weight_matrixs)

      self.layers_errors_reduced = [np.array([])] * len(self.weight_matrixs)
      self.activation_values_reduced = [np.array([])] * len(self.weight_matrixs)

      row_counter = 1
      for index, row in x.iterrows():
        y_predict = self._fowardPropagation(row)
        y_true = y.loc[index]
        dj = []
        for layer_index in reversed(range(len(self.weight_matrixs))):
          if layer_index == len(self.weight_matrixs) - 1: # caso para capa de salida
            dj = 2 * (y_predict - y_true) * self._getDerivativeActivationValues(layer_index, self.net_values[layer_index])
            oj = self._getActivationValue(layer_index, self.net_values[layer_index])

          elif layer_index == 0: # caso para capa de entrada
            dj = (self.weight_matrixs[layer_index + 1] @ dj) * np.append(self._getDerivativeActivationValues(layer_index, self.net_values[layer_index]), 1)
            dj = np.delete(dj, -1) # eliminación del bias
            oj = self.net_values[layer_index]

          else: # caso para capas ocultas
            dj = (self.weight_matrixs[layer_index + 1] @ dj) * np.append(self._getDerivativeActivationValues(layer_index, self.net_values[layer_index]), 1)
            dj = np.delete(dj, -1) # eliminación del bias
            oj = self._getActivationValue(layer_index, self.net_values[layer_index])
          # Generación de matriz de errores
          self.layers_errors[layer_index] = np.append(self.layers_errors[layer_index], np.array(dj))
          self.layers_errors[layer_index] = np.reshape(self.layers_errors[layer_index], (row_counter,dj.shape[0]))
          # Generación de matriz de oj (valores de activación)
          self.activation_values[layer_index] = np.append(self.activation_values[layer_index], np.array(oj))
          self.activation_values[layer_index] = np.reshape(self.activation_values[layer_index], (row_counter,oj.shape[0]))
        # Incremento del row index para el reshape
        row_counter += 1
      

      # Reducir dimensionalidad
      for layer_index in range(len(self.weight_matrixs)):
        for col in range(len(self.layers_errors[layer_index][0])):
          error_mean = np.mean(self.layers_errors[layer_index][:, col])
          activaction_mean = np.mean(self.activation_values[layer_index][:, col])

          self.layers_errors_reduced[layer_index] = np.append(self.layers_errors_reduced[layer_index], error_mean)
          self.activation_values_reduced[layer_index] = np.append(self.activation_values_reduced[layer_index], activaction_mean)

      # apply values to delta w
      for layer_index in reversed(range(len(self.weight_matrixs))):
          if layer_index != 0:
            activation_vec = np.array([self.activation_values_reduced[layer_index - 1]])
            errors_vec = np.array([self.layers_errors_reduced[layer_index]])
            result = activation_vec.T @ errors_vec

            for i in range(len(result)):
              for j in range(len(result[0])):
                self.weight_matrixs[layer_index][i][j] = result[i][j]

      self.error_history.append(self.layers_errors_reduced)

    def step(self):      
      for layer_index in range(len(self.weight_matrixs)):
        self.weight_matrixs[layer_index] = self.weight_matrixs[layer_index] - (self.lr *  self.delta_weight_matrix[layer_index])

      self.epoch += 1

    def _getActivationValue(self, layer_number, values):
      return_values = []
      for value in np.nditer(values):
        return_values.append(self._applyActivation(layer_number, value))
      return np.array(return_values)

    def _getDerivativeActivationValues(self, layer_number, values):
      return_values = []
      for value in np.nditer(values):
        return_values.append(self._applyActivationDerivative(layer_number, value))
      return np.array(return_values)

    def _applyActivation(self, layer_number, value):
      if self.activation[layer_number] == 's': # aplicar función sigmoide
        return sigmoid(value)
      elif self.activation[layer_number] == 't': # aplicar función tangente hiperbólico
        return tanh(value)
      elif self.activation[layer_number] == 'r': # aplicar función relu
        return relu(value)
      elif self.activation[layer_number] == 'l': # aplicar función leaky relu
        return lrelu(value)
      return 0

    def _applyActivationDerivative(self, layer_number, value):
      if self.activation[layer_number] == 's': # aplicar función sigmoide
        return d_sigmoid(value)
      elif self.activation[layer_number] == 't': # aplicar función tangente hiperbólico
        return d_tanh(value)
      elif self.activation[layer_number] == 'r': # aplicar función relu
        return d_relu(value)
      elif self.activation[layer_number] == 'l': # aplicar función leaky relu
        return d_lrelu(value)
      return 0


In [12]:
neural_net = DenseNN([12, 3, 2],['s','s'], 0)
neural_net.train()

for i in range(5):
  neural_net.backPropagation(df_titanic, y)
  neural_net.step()

neural_net.error_history

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


[[array([67881.95036782,  8727.06990055, 96935.93909135]),
  array([ 0.09773937, 25.3554038 ])],
 [array([8.09142819e+12, 1.50457269e+11, 1.30422955e+13]),
  array([-4.88343729e+01, -6.33775847e+06])],
 [array([9.50042867e+28, 2.04561923e+27, 3.15343733e+29]),
  array([2.12548090e+07, 2.36249239e+17])],
 [array([3.81351709e+60, 7.02666302e+58, 6.15293043e+60]),
  array([-2.38403836e+18, -4.46158171e+38])],
 [array([1.87078781e+124, 4.00132141e+122, 6.21862322e+124]),
  array([4.05138667e+40, 9.36611762e+80])]]

In [13]:
neural_net = DenseNN([12, 3, 2],['r','r'], 0)
neural_net.train()

for i in range(5):
  neural_net.backPropagation(df_titanic, y)
  neural_net.step()

neural_net.error_history

[[array([ -45.48425443, -213.65487753,  293.51226294]),
  array([130.30155939,   0.        ])],
 [array([4.04836017e+09, 1.11022896e+09, 4.60653907e+09]),
  array([8.27375571e+05, 5.15002755e+00])],
 [array([1.39557863e+17, 3.82703765e+16, 1.58803569e+17]),
  array([4.72827495e+09, 2.94360907e+04])],
 [array([3.86339038e+24, 1.05944158e+24, 4.39617067e+24]),
  array([2.41767586e+13, 1.50513514e+08])],
 [array([8.47975276e+31, 2.32536756e+31, 9.64915182e+31]),
  array([1.09885630e+17, 6.84098006e+11])]]

In [14]:
neural_net = DenseNN([12, 5, 6, 2],['s', 's','r'], 0)
neural_net.train()

for i in range(5):
  neural_net.backPropagation(df_titanic, y)
  neural_net.step()

neural_net.error_history

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


[[array([  30195.28482588, -105934.84230162,    1098.62033618,
          158568.84708647,   32451.2614224 ]),
  array([  7.89793111,   1.05351558, -68.63848912,   0.47804373,
          -0.80754907,  -0.40975193]),
  array([7.23971936, 0.        ])],
 [array([-1.84131644e+16, -3.97520538e+16, -8.51066558e+14, -3.02209951e+16,
         -4.18625437e+15]),
  array([-4.83148266e+07, -1.32027837e+06, -9.29231636e+09, -2.31204865e+05,
         -9.59848084e+05, -2.49774470e+05]),
  array([22.37232709,  0.        ])],
 [array([3.09250512e+37, 8.39571644e+37, 1.25172445e+36, 5.02080964e+37,
         7.15086140e+36]),
  array([-9.68633035e+20, -7.20267370e+17,  1.26766487e+23, -2.21573361e+16,
          1.03029743e+15,  4.26963283e+13]),
  array([1.60299211, 0.        ])],
 [array([-4.15068424e+76, -1.23559938e+77, -1.56643334e+75, -6.70528208e+76,
         -9.68035760e+75]),
  array([-5.79437839e+44,  2.30443817e+38,  1.43118764e+49, -1.68149690e+35,
          7.20135168e+32,  7.56844576e+29]),


¿Se va reduciendo el error? Intente diferentes combinaciones de parámetros, arquitecturas y funciones de activación para lograr que su algoritmo converja. 

¿Cuál combinación le produjo el mejor resultado?

> Como se puede ver en los resultado, los valores de los errores de las neuronas van covergiendo pero para constantes muy altas. Inclusive, para las funciones. Esto se debe a la implementación de limites que se está manejando dentro de las funciones matemáticas. Consideramos que, entre varias configuraciones, la que maneja mejor consistencia es la úlitma que maneja `DenseNN([12, 5, 6, 2],['s', 's','r'], 0)`

¿Qué aprendió de estos experimentos? (Se vale no haber aprendido nada, venimos a
experimentar)

> Dentro de estos experimentos se tuvo un entendimiento más amplio sobre el uso del gradiente del descenso. Además, se aprendió de como se debe mantener un buen registro y cálculo del error para el cálculo de backpropagation.



In [ ]:
jupyter nbconvert --to html /PATH/TO/YOUR/NOTEBOOKFILE.ipynb